// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"

	"github.com/zgsm-ai/codebase-indexer/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {




	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/search/semantic",
				Handler: semanticSearchHandler(serverCtx),
			},
		},
		rest.WithPrefix("/codebase-embedder"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/embeddings",
				Handler: deleteIndexHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/embeddings/summary",
				Handler: summaryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/files/token",
				Handler: TokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/files/upload",
				Handler: taskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/files/status",
				Handler: StatusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/codebase-embedder"),
	)

	// 添加代码库查询接口路由
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/codebase/query",
				Handler: NewQueryCodebaseHandler(serverCtx).QueryCodebase,
			},
		},
		rest.WithPrefix("/codebase-embedder"),
	)
}
