apiVersion: v1
kind: ConfigMap
metadata:
  name: codebase-embedder-config
  namespace: costrict
data:
  conf.yaml: |
    Name: codebase-embedder
    Host: 0.0.0.0
    Port: 8888
    Timeout: 120000 #ms
    MaxConns: 500
    MaxBytes: 104857600 # 100MB
    DevServer:
      Enabled: true
    Verbose: false
    Mode: test # dev,test,rt,pre, pro
      
    Auth:
      UserInfoHeader: "x-userinfo"
    Database:
      Driver: postgres
      DataSource: postgres://postgres:costrict@postgres-postgresql-primary.costrict.svc.cluster.local:5432/codebase_embedder?sslmode=disable
      AutoMigrate:
        enable: true    
    IndexTask:
      PoolSize: 1000
      QueueSize: 100
      LockTimeout: 10s
      EmbeddingTask:
        PoolSize: 20
        MaxConcurrency: 10
        Timeout: 18000s
        OverlapTokens: 100
        MaxTokensPerChunk: 1000
        EnableMarkdownParsing: false
        EnableOpenAPIParsing: false
      GraphTask:
        MaxConcurrency: 100
        Timeout: 18000s
        ConfFile: "etc/codegraph.yaml"
    
    Cleaner:
      Cron: "0 0 * * *"
      CodebaseExpireDays: 30
    
    Redis:
      Addr: costrict-redis-master.costrict.svc.cluster.local:6379
      DefaultExpiration: 1h
    
    VectorStore:
      Type: weaviate
      Timeout: 60s
      MaxRetries: 5
      StoreSourceCode: false
      FetchSourceCode: true
      BaseURL: http://codebase-querier-svc.costrict:8888/codebase-indexer/api/v1/snippets/read
      Weaviate:
        MaxDocuments: 20
        Endpoint: "weaviate-service.costrict.svc.cluster.local:8080"
        BatchSize: 100
        ClassName: "CodebaseIndex"
      Embedder:
        Timeout: 30s
        MaxRetries: 3
        BatchSize: 10
        StripNewLines: true
        Model: gte-modernbert-base
        ApiKey: "sk-xpiL5eRv65f8LKO8Ac9f1f66702c4f769f0794Ea0cF6B6Db"
        ApiBase: http://10.20.19.2:32326/v1/embeddings
      Reranker:
        Timeout: 10s
        MaxRetries: 3
        Model: gte-reranker-modernbert-base
        ApiKey: "sk-xpiL5eRv65f8LKO8Ac9f1f66702c4f769f0794Ea0cF6B6Db"
        ApiBase: http://10.20.19.2:32323/v1/rerank
    
    Log:
      Mode: console # console,file,volume
      ServiceName: "codebase-embedder"
      Encoding: plain # json,plain
      Path: "/app/logs"
      Level: info # debug,info,error,severe
      KeepDays: 7
      MaxSize: 100 # MB per file, take affect when Rotation is size.
      Rotation: daily # split by day or size
    Validation:
      enabled: true
      check_content: true
      fail_on_mismatch: false
      log_level: "info"
      max_concurrency: 5
      skip_patterns: []
    TokenLimit:
      max_running_tasks: 100  
      enabled: true 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codebase-embedder
  namespace: costrict
  labels:
    app: codebase-embedder
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codebase-embedder
  template:
    metadata:
      labels:
        app: codebase-embedder
    spec:
      containers:
      - name: codebase-embedder
        image: zgsm/codebase-embedder:v0.1.0
        imagePullPolicy: IfNotPresent
        command:
          - /app/server
          - -f
          - /app/conf/conf.yaml
        ports:
        - containerPort: 8888
          name: http
        - containerPort: 6060
          name: metrics
        env:
          - name: TZ
            value: Asia/Shanghai
          - name: INDEX_NODE
            value: "1"
        livenessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "4"
            memory: 8Gi
          limits:
            cpu: "8"
            memory: 16Gi
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: app-conf
          mountPath: /app/conf
      volumes:
        - name: app-conf
          configMap:
            name: codebase-embedder-config
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: codebase-embedder-svc
  namespace: costrict
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    name: http
    nodePort: 32002
  - port: 6470
    targetPort: 6060
    name: metrics
  selector:
    app: codebase-embedder
